[workspace]
members = [ "chap7_proj_structure", "common_collection", "common_concepts", "enums_patterns", 
    "guessing_game",
    "hello_world"
, "ownership", "programs", "struct_datatype"]
resolver="3"
